### ISSUE TITLE
App does not start / launching fails

### ISSUE THREAD

**Issue by SparkyCola** [rmtheis/android-ocr#31]
Hi, i've got Android OCR installed. When i try to start it nothing happen. Logcat shows this mesage:
10-04 22:24:46.786    8726-8726/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: edu.sfsu.cs.orange.ocr, PID: 8726
    java.lang.NoSuchFieldError: no "J" field "mNativeData" in class "Lcom/googlecode/tesseract/android/TessBaseAPI;" or its superclasses
            at com.googlecode.tesseract.android.TessBaseAPI.nativeClassInit(Native Method)
            at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(Unknown Source)
            at edu.sfsu.cs.orange.ocr.CaptureActivity.onResume(Unknown Source)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
            at android.app.Activity.performResume(Activity.java:6076)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3009)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3051)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2426)
            at android.app.ActivityThread.access$900(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5354)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

I've got a Sony Xperia SP with Cyanogenmod 12 (Android 5.1.1).

**Comment by rmtheis** [comment]
The pre-compiled library you're using is too old. You need to build using the build instructions.
